spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://gad-dev:12345@localhost:27017/inventory?authSource=admin
logging:
  level:
    org.springframework.data.mongodb: DEBUG