spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://gad-dev:12345@localhost:27017/inventory?authSource=admin
      database: inventory
      auto-index-creation: true
  webflux:
    multipart:
      max-in-memory-size: 10MB
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.gad.inventory_service.DataInitializer: DEBUG
    reactor.core: DEBUG
    com.mongodb: DEBUG

auth:
  token:
    jwt-secret: 123456789
    expiration-in-millis: 86400000