spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://gad-dev:12345@localhost:27017/inventory?authSource=admin
logging:
  level:
    org.springframework.data.mongodb: DEBUG
auth:
  token:
    jwt-secret: 123456789
    expiration-in-millis: 86400000